### ISSUE TITLE
feat: add ability to influence component processing order

### ISSUE THREAD

**Issue by B13rg** [ice-bergtech/kr8#70]
Add a way for a group of components to be processed in a user-defined order.
Only apply to components with the field.
First process numbered components serially, then un-numbered.

Not sure if it should go smal -> large or large -> small

In cluster kr8_spec:

```yaml
{
_kr8_spec: {
  _components: {
  cmpA: { path : '/dir', weight: 10  },
  cmpB: { path : '/dir', weight: 20 },
 cmpC: { path : '/dir' },
 cmpD: { path : '/dir' },
}
}
}
```

Does:

```
Generate cmpA
Generate cmpB
threaded: Generate cmpC, cmpD
```
